Repository Idea-Archive/Idea-Archive-iOS, pull requests merged in 2023-08, with the labels that each got.

#27 App Transport Security Settings에 Allow Arbitary Loads 추가
  Idea-Archive/Support/Info.plist
Labels: feature

#30 body가 아닌 header에 넣을 수 있게 수정, request 부분 수정
  Idea-Archive/Sources/Data/General/BaseURL.swift
  Idea-Archive/Sources/Data/General/Idea-Archive++Bundle.swift
  Idea-Archive/Sources/Data/Request/Auth/AuthRequest.swift
  Idea-Archive/Sources/Data/Services/Auth/AuthServices.swift
Labels: enhancement

#39 로그인 페이지 퍼블리싱
  Idea-Archive.xcodeproj/project.pbxproj
  Idea-Archive/Sources/Presentation/Login/View/LoginVC.swift
Labels: enhancement, help wanted

#45 :ambulance: :: [44] projectSetting
  .gitignore
  Idea-Archive.xcodeproj/project.pbxproj
  Idea-Archive.xcodeproj/xcshareddata/xcschemes/Idea-Archive.xcscheme
  Idea-Archive/Sources/Presentation/Signup/CertificationNumber/CertificationNumberVC.swift
  Idea-Archive/Support/BaseURL.plist
Labels: bug

#40 :lipstick: 로그인 페이지를 퍼블리싱 합니다.
  Idea-Archive/Sources/Presentation/Login/View/LoginVC.swift
Labels: enhancement

#50 [49] Project / dependencies IQKeyboardManagerSwift 수정
  Idea-Archive.xcworkspace/contents.xcworkspacedata
  Project.swift
Labels: bug
